Repository WebKit/Speedometer, pull requests merged in 2023-05, with the labels that each got.

#160 Run the build scripts for all vanilla examples
  resources/todomvc/vanilla-examples/javascript-es5/dist/controller.js
  resources/todomvc/vanilla-examples/javascript-es5/dist/helpers.js
  resources/todomvc/vanilla-examples/javascript-es5/dist/model.js
  resources/todomvc/vanilla-examples/javascript-es5/dist/store.js
  resources/todomvc/vanilla-examples/javascript-es5/dist/template.js
  resources/todomvc/vanilla-examples/javascript-es5/dist/view.js
  resources/todomvc/vanilla-examples/javascript-es6-webpack/dist/app.bundle.js.map
  resources/todomvc/vanilla-examples/javascript-es6/dist/controller.js
  resources/todomvc/vanilla-examples/javascript-es6/dist/helpers.js
  resources/todomvc/vanilla-examples/javascript-es6/dist/model.js
  resources/todomvc/vanilla-examples/javascript-es6/dist/store.js
  resources/todomvc/vanilla-examples/javascript-es6/dist/template.js
  resources/todomvc/vanilla-examples/javascript-es6/dist/view.js
Labels: trivial change

#161 Remove base element from angular example. This allows the benchmark to be ran on a subdirectory.
  resources/todomvc/architecture-examples/angular/dist/index.html
  resources/todomvc/architecture-examples/angular/src/index.html
Labels: non-trivial change, v3-blocker

#171 Make confidenceIntervalDelta work with more than 100 degrees of freedom.
  resources/statistics.mjs
Labels: trivial change

#170 position iframe
  resources/benchmark-runner.mjs
  resources/main.mjs
  tests/benchmark-runner-tests.mjs
Labels: non-trivial change

#168 [TodoMVC]: replace crypto.randomUUID
  resources/todomvc/architecture-examples/react-redux/dist/app.bundle.js
  resources/todomvc/architecture-examples/react-redux/dist/app.bundle.js.map
  resources/todomvc/architecture-examples/react-redux/dist/app.css.map
  resources/todomvc/architecture-examples/react-redux/src/reducers/todos.js
  resources/todomvc/architecture-examples/react-redux/src/test/setup.js
  resources/todomvc/architecture-examples/react/dist/app.bundle.js
  resources/todomvc/architecture-examples/react/dist/app.bundle.js.LICENSE.txt
  resources/todomvc/architecture-examples/react/dist/app.bundle.js.map
  resources/todomvc/architecture-examples/react/dist/app.css.map
  resources/todomvc/architecture-examples/react/src/todo/reducer.js
  resources/todomvc/architecture-examples/vue/src/components/TodosComponent.vue
Labels: non-trivial change

#166 add a basic developer mode ui on the main runner
  resources/developer-mode.mjs
  resources/main.css
  resources/main.mjs
  resources/tests.mjs
Labels: non-trivial change

#180 newssite - potential fix for test
  resources/tests.mjs
Labels: non-trivial change

#183 Add a meta viewport tag so that the viewport ias always the same size…
  InteractiveRunner.html
  index.html
Labels: non-trivial change

#181 Remove Stockcharts-Canvas steps
  resources/tests.mjs
Labels: non-trivial change

#164 Refactor test callbacks into TestInvoker class.
  resources/benchmark-runner.mjs
  tests/benchmark-runner-tests.mjs
Labels: non-trivial change

#188 Additional developerMode controls
  resources/developer-mode.mjs
  resources/main.css
  resources/params.mjs
Labels: trivial change

#189 Adjust the multiplier to convert geomean so that scores are less than 50 in even the fastest browser/device.
  resources/benchmark-runner.mjs
  tests/benchmark-runner-tests.mjs
Labels: major change

#194 Developer Mode UI improvements
  resources/developer-mode.mjs
Labels: trivial change

#190 Add more markers
  resources/benchmark-runner.mjs
  tests/benchmark-runner-tests.mjs
Labels: non-trivial change

#192 Better copy-support for detailed results table
  resources/main.css
  resources/metric-ui.mjs
Labels: trivial change

#191 npm run format
  .eslintignore
  .prettierignore
  resources/developer-mode.mjs
  resources/tentative/complex-static-html/src/big-dom-generator/components/analytics-pop-over.jsx
  resources/tentative/complex-static-html/src/big-dom-generator/components/date-picker.jsx
  resources/tentative/complex-static-html/src/big-dom-generator/components/filter-pop-over.jsx
  resources/tentative/complex-static-html/src/big-dom-generator/components/pop-over.jsx
  resources/tentative/complex-static-html/src/big-dom-generator/components/table.jsx
  resources/tentative/complex-static-html/src/big-dom-generator/components/top-bar.jsx
  resources/tentative/complex-static-html/src/big-dom-generator/components/tree-area.jsx
  resources/tentative/complex-static-html/src/big-dom-generator/gen-css.js
  resources/tentative/editors/codemirror.js
  resources/tentative/editors/tiptap.js
Labels: trivial change

#149 Add a workload with Chart.js
  resources/tentative/charts/README.md
  resources/tentative/charts/chartjs.html
  resources/tentative/charts/chartjs.js
  resources/tentative/charts/developer.html
  resources/tentative/charts/dist/assets/chartjs-7fd89fd7.js
  resources/tentative/charts/dist/assets/flights-airports-9a9e6422.js
  resources/tentative/charts/dist/assets/plot-37d2a5fb.js
  resources/tentative/charts/dist/chartjs.html
  resources/tentative/charts/dist/developer.html
  resources/tentative/charts/dist/index.html
  resources/tentative/charts/dist/observable-plot.html
  resources/tentative/charts/index.html
  resources/tentative/charts/package-lock.json
  resources/tentative/charts/package.json
  resources/tentative/charts/vite.config.js
  resources/tests.mjs
Labels: non-trivial change

#196 Add warmupBeforeSync parameter, which triggers 100ms of infinite loop before each sync step.
  resources/benchmark-runner.mjs
  resources/params.mjs
Labels: trivial change
