Repository WebKit/Speedometer, pull requests merged in 2023-06, with the labels that each got.

#205 [codemirror] Mock requestAnimationFrame to setTimeout so that we don'…
  resources/tentative/editors/codemirror.html
  resources/tentative/editors/dist/assets/codemirror-77870192.js
  resources/tentative/editors/dist/assets/tiptap-39715a58.js
  resources/tentative/editors/dist/codemirror.html
  resources/tentative/editors/dist/tiptap.html
Labels: non-trivial change

#159 Replace innerHTML by DOMParser in a workload
  resources/todomvc/vanilla-examples/javascript-es5/dist/view.js
  resources/todomvc/vanilla-examples/javascript-es5/src/view.js
Labels: non-trivial change

#210 Add stricter _parseInt helper to Params
  resources/params.mjs
Labels: trivial change

#209 Freeze params again in non-developerMode
  resources/benchmark-runner.mjs
  resources/params.mjs
  resources/tentative/editors/tiptap.js
Labels: trivial change

#202 Add param.waitBeforeSync
  resources/benchmark-runner.mjs
  resources/params.mjs
Labels: non-trivial change

#212 Fix params parsing
  resources/params.mjs
Labels: trivial change

#213 Show version number
  index.html
  resources/main.css
Labels: trivial change

#200 Reduce the react stockcharts steps
  resources/tests.mjs
Labels: non-trivial change

#218 Fix broken tests - add tags to nuxt app
  resources/tests.mjs
Labels: trivial change

#227 Show version number in all sections
  index.html
Labels: trivial change

#222 Add the missing tags to perf dashboard workload.
  resources/tests.mjs
Labels: trivial change

#230 run format on all
  resources/tests.mjs
  resources/todomvc/architecture-examples/vue/src/App.vue
Labels: trivial change

#228 Display iteration marker in progress bar
  resources/main.css
  resources/main.mjs
Labels: trivial change

#232 Newssite css: cleanup
  .eslintignore
  .prettierignore
  resources/tentative/newssite/news-site-css/.stylelintrc.json
  resources/tentative/newssite/news-site-css/README.md
  resources/tentative/newssite/news-site-css/dist/article.css
  resources/tentative/newssite/news-site-css/dist/article.module.css
  resources/tentative/newssite/news-site-css/dist/button.css
  resources/tentative/newssite/news-site-css/dist/button.module.css
  resources/tentative/newssite/news-site-css/dist/dropdown.css
  resources/tentative/newssite/news-site-css/dist/dropdown.module.css
  resources/tentative/newssite/news-site-css/dist/form.css
  resources/tentative/newssite/news-site-css/dist/form.module.css
  resources/tentative/newssite/news-site-css/dist/global.css
  resources/tentative/newssite/news-site-css/dist/header.css
  resources/tentative/newssite/news-site-css/dist/header.module.css
  resources/tentative/newssite/news-site-css/dist/icons.css
  resources/tentative/newssite/news-site-css/dist/icons.module.css
  resources/tentative/newssite/news-site-css/dist/index.css
  resources/tentative/newssite/news-site-css/dist/index.min.css
  resources/tentative/newssite/news-site-css/dist/input.css
  resources/tentative/newssite/news-site-css/dist/input.module.css
  resources/tentative/newssite/news-site-css/dist/modal.css
  resources/tentative/newssite/news-site-css/dist/modal.module.css
  resources/tentative/newssite/news-site-css/dist/navbar.css
  resources/tentative/newssite/news-site-css/dist/navbar.module.css
  resources/tentative/newssite/news-site-css/dist/partials.css
  resources/tentative/newssite/news-site-css/dist/sitemap.css
  resources/tentative/newssite/news-site-css/dist/sitemap.module.css
  resources/tentative/newssite/news-site-css/dist/variables.css
  resources/tentative/newssite/news-site-css/dist/variables.module.css
  resources/tentative/newssite/news-site-css/package-lock.json
  resources/tentative/newssite/news-site-css/package.json
  resources/tentative/newssite/news-site-css/rollup.config.js
  resources/tentative/newssite/news-site-css/src/css/article.css
  resources/tentative/newssite/news-site-css/src/css/button.css
  resources/tentative/newssite/news-site-css/src/css/dropdown.css
  resources/tentative/newssite/news-site-css/src/css/form.css
  resources/tentative/newssite/news-site-css/src/css/global.css
  resources/tentative/newssite/news-site-css/src/css/header.css
  resources/tentative/newssite/news-site-css/src/css/icons.css
  resources/tentative/newssite/news-site-css/src/css/input.css
  resources/tentative/newssite/news-site-css/src/css/modal.css
  resources/tentative/newssite/news-site-css/src/css/navbar.css
  resources/tentative/newssite/news-site-css/src/css/partials.css
  resources/tentative/newssite/news-site-css/src/css/sitemap.css
  resources/tentative/newssite/news-site-css/src/css/variables.css
  resources/tentative/newssite/news-site-css/src/js/index.js
Labels: trivial change

#217 Developer Mode: Support filtering by tags
  resources/developer-mode.mjs
  resources/main.css
  resources/tests.mjs
Labels: trivial change

#241 Undefine requestIdleCallback in the code mirror test for consistency.
  resources/editors/codemirror.html
Labels: non-trivial change

#243 Undefine requestIdleCallback in the Next test for consistency.
  resources/newssite/news-next/dist/404.html
  resources/newssite/news-next/dist/_next/static/F195PZl4yn18BfMZaSMUr/_buildManifest.js
  resources/newssite/news-next/dist/_next/static/F195PZl4yn18BfMZaSMUr/_ssgManifest.js
  resources/newssite/news-next/dist/_next/static/chunks/pages/_app-2761409d330b4b25.js
  resources/newssite/news-next/dist/_next/static/chunks/pages/_app-77983e68be50f72a.js
  resources/newssite/news-next/dist/index.html
  resources/newssite/news-next/src/pages/_app.js
Labels: non-trivial change

#233 Use progress element
  index.html
  resources/main.css
  resources/main.mjs
Labels: trivial change

#253 Adjusting Page.querySelector / Page.querySelectorAll
  resources/benchmark-runner.mjs
Labels: trivial change

#220 [charts] Group substeps to make them more stable
  resources/tests.mjs
Labels: non-trivial change

#239 Add Complex DOM required changes to standalone TodoMVC apps
  resources/tests.mjs
  resources/todomvc/architecture-examples/angular/dist/index.html
  resources/todomvc/architecture-examples/angular/dist/main.47f1891b70562df3.js
  resources/todomvc/architecture-examples/angular/dist/main.bb47296fc27e3427.js
  resources/todomvc/architecture-examples/angular/src/app/todo-item/todo-item.component.html
  resources/todomvc/architecture-examples/angular/src/app/todo-item/todo-item.component.ts
  resources/todomvc/architecture-examples/angular/src/app/todo-list/todo-list.component.html
  resources/todomvc/architecture-examples/backbone/dist/index.html
  resources/todomvc/architecture-examples/backbone/dist/views/app-view.js
  resources/todomvc/architecture-examples/backbone/index.html
  resources/todomvc/architecture-examples/backbone/src/views/app-view.js
  resources/todomvc/architecture-examples/jquery/dist/index.html
  resources/todomvc/architecture-examples/jquery/index.html
  resources/todomvc/architecture-examples/preact/dist/app.js
  resources/todomvc/architecture-examples/preact/dist/app.js.map
  resources/todomvc/architecture-examples/preact/src/app/app.js
  resources/todomvc/architecture-examples/preact/src/app/item.js
  resources/todomvc/architecture-examples/preact/src/app/main.js
  resources/todomvc/architecture-examples/react-redux/dist/app.bundle.js
  resources/todomvc/architecture-examples/react-redux/dist/app.bundle.js.map
  resources/todomvc/architecture-examples/react-redux/src/components/item.jsx
  resources/todomvc/architecture-examples/react-redux/src/components/main.jsx
  resources/todomvc/architecture-examples/react/dist/app.bundle.js
  resources/todomvc/architecture-examples/react/dist/app.bundle.js.map
  resources/todomvc/architecture-examples/react/src/todo/components/item.jsx
  resources/todomvc/architecture-examples/react/src/todo/components/main.jsx
  resources/todomvc/architecture-examples/svelte/dist/app.js
  resources/todomvc/architecture-examples/svelte/dist/app.js.map
  resources/todomvc/architecture-examples/svelte/src/App.svelte
  resources/todomvc/architecture-examples/svelte/src/Item.svelte
  resources/todomvc/architecture-examples/vue/dist/index.html
  resources/todomvc/architecture-examples/vue/dist/js/app.25bf5185.js
  resources/todomvc/architecture-examples/vue/dist/js/app.25bf5185.js.map
  resources/todomvc/architecture-examples/vue/dist/js/app.570d8133.js
  resources/todomvc/architecture-examples/vue/dist/js/app.570d8133.js.map
  resources/todomvc/architecture-examples/vue/src/components/TodoItem.vue
  resources/todomvc/architecture-examples/vue/src/components/TodosComponent.vue
  resources/todomvc/vanilla-examples/javascript-es5/dist/index.html
  resources/todomvc/vanilla-examples/javascript-es5/dist/template.js
  resources/todomvc/vanilla-examples/javascript-es5/index.html
  resources/todomvc/vanilla-examples/javascript-es5/src/template.js
  resources/todomvc/vanilla-examples/javascript-es6-webpack/dist/app.bundle.js
  resources/todomvc/vanilla-examples/javascript-es6-webpack/dist/app.bundle.js.map
  resources/todomvc/vanilla-examples/javascript-es6-webpack/dist/index.html
  resources/todomvc/vanilla-examples/javascript-es6-webpack/src/index.html
  resources/todomvc/vanilla-examples/javascript-es6-webpack/src/template.js
  resources/todomvc/vanilla-examples/javascript-es6/dist/index.html
  resources/todomvc/vanilla-examples/javascript-es6/dist/template.js
  resources/todomvc/vanilla-examples/javascript-es6/index.html
  resources/todomvc/vanilla-examples/javascript-es6/src/template.js
Labels: non-trivial change

#255 Move the initial glyph cache cost out of the measured part of the perf dashboard workload.
  resources/tentative/perf.webkit.org/public/v3/index.html
  resources/tests.mjs
Labels: non-trivial change

#249 [OPTIONAL]: TodoMVC built with Web Components
  .eslintignore
  .prettierignore
  resources/tests.mjs
  resources/todomvc/vanilla-examples/javascript-web-components/.gitignore
  resources/todomvc/vanilla-examples/javascript-web-components/index.html
  resources/todomvc/vanilla-examples/javascript-web-components/package-lock.json
  resources/todomvc/vanilla-examples/javascript-web-components/package.json
  resources/todomvc/vanilla-examples/javascript-web-components/src/components/todo-app/todo-app.component.js
  resources/todomvc/vanilla-examples/javascript-web-components/src/components/todo-app/todo-app.template.js
  resources/todomvc/vanilla-examples/javascript-web-components/src/components/todo-bottombar/todo-bottombar.component.js
  resources/todomvc/vanilla-examples/javascript-web-components/src/components/todo-bottombar/todo-bottombar.template.js
  resources/todomvc/vanilla-examples/javascript-web-components/src/components/todo-item/todo-item.component.js
  resources/todomvc/vanilla-examples/javascript-web-components/src/components/todo-item/todo-item.template.js
  resources/todomvc/vanilla-examples/javascript-web-components/src/components/todo-list/todo-list.component.js
  resources/todomvc/vanilla-examples/javascript-web-components/src/components/todo-list/todo-list.template.js
  resources/todomvc/vanilla-examples/javascript-web-components/src/components/todo-topbar/todo-topbar.component.js
  resources/todomvc/vanilla-examples/javascript-web-components/src/components/todo-topbar/todo-topbar.template.js
  resources/todomvc/vanilla-examples/javascript-web-components/src/hooks/useDoubleClick.js
  resources/todomvc/vanilla-examples/javascript-web-components/src/hooks/useKeyListener.js
  resources/todomvc/vanilla-examples/javascript-web-components/src/hooks/useRouter.js
  resources/todomvc/vanilla-examples/javascript-web-components/src/styles/app.constructable.js
  resources/todomvc/vanilla-examples/javascript-web-components/src/styles/bottombar.constructable.js
  resources/todomvc/vanilla-examples/javascript-web-components/src/styles/footer.css
  resources/todomvc/vanilla-examples/javascript-web-components/src/styles/global.constructable.js
  resources/todomvc/vanilla-examples/javascript-web-components/src/styles/global.css
  resources/todomvc/vanilla-examples/javascript-web-components/src/styles/header.css
  resources/todomvc/vanilla-examples/javascript-web-components/src/styles/main.constructable.js
  resources/todomvc/vanilla-examples/javascript-web-components/src/styles/todo-item.constructable.js
  resources/todomvc/vanilla-examples/javascript-web-components/src/styles/todo-list.constructable.js
  resources/todomvc/vanilla-examples/javascript-web-components/src/styles/topbar.constructable.js
  resources/todomvc/vanilla-examples/javascript-web-components/src/utils/nanoid.js
Labels: non-trivial change

#252 Move the charts workload out of the tentative directory
  .eslintignore
  .gitignore
  .prettierignore
  resources/charts/README.md
  resources/charts/chartjs.html
  resources/charts/chartjs.js
  resources/charts/datasets/README
  resources/charts/datasets/airports.csv
  resources/charts/datasets/flights-airports.csv
  resources/charts/developer.html
  resources/charts/dist/assets/chartjs-7fd89fd7.js
  resources/charts/dist/assets/flights-airports-9a9e6422.js
  resources/charts/dist/assets/plot-37d2a5fb.js
  resources/charts/dist/chartjs.html
  resources/charts/dist/developer.html
  resources/charts/dist/index.html
  resources/charts/dist/observable-plot.html
  resources/charts/index.html
  resources/charts/observable-plot.html
  resources/charts/observable-plot.js
  resources/charts/package-lock.json
  resources/charts/package.json
  resources/charts/vite.config.js
  resources/tests.mjs
Labels: non-trivial change

#261 Run the format script after javascript web components landed
  resources/todomvc/vanilla-examples/javascript-web-components/src/utils/nanoid.js
Labels: trivial change

#260 TodoMVC - Web Components - udpate test text
  resources/tests.mjs
Labels: trivial change

#254 [OPTIONAL] - updated todomvc styles
  resources/todomvc/todomvc-css/.gitignore
  resources/todomvc/todomvc-css/.stylelintrc.json
  resources/todomvc/todomvc-css/README.md
  resources/todomvc/todomvc-css/dist/app.constructable.js
  resources/todomvc/todomvc-css/dist/app.css
  resources/todomvc/todomvc-css/dist/app.module.css
  resources/todomvc/todomvc-css/dist/bottombar.constructable.js
  resources/todomvc/todomvc-css/dist/bottombar.css
  resources/todomvc/todomvc-css/dist/bottombar.module.css
  resources/todomvc/todomvc-css/dist/footer.constructable.js
  resources/todomvc/todomvc-css/dist/footer.css
  resources/todomvc/todomvc-css/dist/footer.module.css
  resources/todomvc/todomvc-css/dist/global.constructable.js
  resources/todomvc/todomvc-css/dist/global.css
  resources/todomvc/todomvc-css/dist/header.constructable.js
  resources/todomvc/todomvc-css/dist/header.css
  resources/todomvc/todomvc-css/dist/header.module.css
  resources/todomvc/todomvc-css/dist/index.css
  resources/todomvc/todomvc-css/dist/index.html
  resources/todomvc/todomvc-css/dist/index.js
  resources/todomvc/todomvc-css/dist/index.min.css
  resources/todomvc/todomvc-css/dist/main.constructable.js
  resources/todomvc/todomvc-css/dist/main.css
  resources/todomvc/todomvc-css/dist/main.module.css
  resources/todomvc/todomvc-css/dist/partials.css
  resources/todomvc/todomvc-css/dist/todo-item.constructable.js
  resources/todomvc/todomvc-css/dist/todo-item.css
  resources/todomvc/todomvc-css/dist/todo-item.module.css
  resources/todomvc/todomvc-css/dist/todo-list.constructable.js
  resources/todomvc/todomvc-css/dist/todo-list.css
  resources/todomvc/todomvc-css/dist/todo-list.module.css
  resources/todomvc/todomvc-css/dist/topbar.constructable.js
  resources/todomvc/todomvc-css/dist/topbar.css
  resources/todomvc/todomvc-css/dist/topbar.module.css
  resources/todomvc/todomvc-css/index.html
  resources/todomvc/todomvc-css/package-lock.json
  resources/todomvc/todomvc-css/package.json
  resources/todomvc/todomvc-css/plugins/constructable-css/index.js
  resources/todomvc/todomvc-css/rollup.config.js
  resources/todomvc/todomvc-css/screenshot.png
  resources/todomvc/todomvc-css/src/css/app.css
  resources/todomvc/todomvc-css/src/css/bottombar.css
  resources/todomvc/todomvc-css/src/css/footer.css
  resources/todomvc/todomvc-css/src/css/global.css
  resources/todomvc/todomvc-css/src/css/header.css
  resources/todomvc/todomvc-css/src/css/main.css
  resources/todomvc/todomvc-css/src/css/partials.css
  resources/todomvc/todomvc-css/src/css/todo-item.css
  resources/todomvc/todomvc-css/src/css/todo-list.css
  resources/todomvc/todomvc-css/src/css/topbar.css
  resources/todomvc/todomvc-css/src/js/index.js
Labels: trivial change

#251 Add a Lit TodoMVC app
  .eslintignore
  .prettierignore
  resources/tests.mjs
  resources/todomvc/architecture-examples/lit/.gitignore
  resources/todomvc/architecture-examples/lit/README.md
  resources/todomvc/architecture-examples/lit/dist/index.html
  resources/todomvc/architecture-examples/lit/dist/index.js
  resources/todomvc/architecture-examples/lit/index.html
  resources/todomvc/architecture-examples/lit/package-lock.json
  resources/todomvc/architecture-examples/lit/package.json
  resources/todomvc/architecture-examples/lit/rollup.config.mjs
  resources/todomvc/architecture-examples/lit/src/index.ts
  resources/todomvc/architecture-examples/lit/src/lib/events.ts
  resources/todomvc/architecture-examples/lit/src/lib/todo-app.ts
  resources/todomvc/architecture-examples/lit/src/lib/todo-footer.ts
  resources/todomvc/architecture-examples/lit/src/lib/todo-form.ts
  resources/todomvc/architecture-examples/lit/src/lib/todo-item.ts
  resources/todomvc/architecture-examples/lit/src/lib/todo-list.ts
  resources/todomvc/architecture-examples/lit/src/lib/todo.css.ts
  resources/todomvc/architecture-examples/lit/src/lib/todos.ts
  resources/todomvc/architecture-examples/lit/src/lib/utils.ts
  resources/todomvc/architecture-examples/lit/tsconfig.json
  resources/todomvc/architecture-examples/lit/web-dev-server.config.js
Labels: non-trivial change

#262 Change the default measurement method to rAF-based approach
  resources/params.mjs
Labels: major change
