Repository WebKit/Speedometer, pull requests merged in 2024-01, with the labels that each got.

#342 Always instantiate Float32Array in the cost array of findOptimalSegmentationInternal.
  resources/perf.webkit.org/public/shared/statistics.js
  resources/perf.webkit.org/public/v3/bundled-scripts.js
Labels: non-trivial change

#349 Allow empty hash for cleaner default URLs on the home screen
  resources/main.css
  resources/main.mjs
Labels: trivial change

#353 Fix navigation for Firefox
  resources/main.mjs
Labels: trivial change, v3-blocker

#354 Update document title
  index.html
  resources/main.mjs
Labels: trivial change

#364 TodoMVC jQuery: fix clear completed button
  resources/todomvc/architecture-examples/jquery-complex/dist/app.js
  resources/todomvc/architecture-examples/jquery-complex/dist/index.html
  resources/todomvc/architecture-examples/jquery/dist/app.js
  resources/todomvc/architecture-examples/jquery/dist/index.html
  resources/todomvc/architecture-examples/jquery/index.html
  resources/todomvc/architecture-examples/jquery/package.json
  resources/todomvc/architecture-examples/jquery/src/app.js
Labels: v3-blocker
