Repository WebKit/Speedometer, pull requests merged in 2024-03, with the labels that each got.

#384 Update about.html to link to each test's GitHub directories instead of directly linking to README.md files.
  about.html
Labels: trivial change, v3-blocker

#387 run format command from root
  README.md
Labels: trivial change

#386 Todomvc-vue: source-map creation
  resources/todomvc/architecture-examples/vue-complex/dist/index.html
  resources/todomvc/architecture-examples/vue-complex/dist/js/app.414e2dd1.js
  resources/todomvc/architecture-examples/vue-complex/dist/js/app.414e2dd1.js.map
  resources/todomvc/architecture-examples/vue-complex/dist/js/app.ad36df07.js
  resources/todomvc/architecture-examples/vue-complex/dist/js/app.ad36df07.js.map
  resources/todomvc/architecture-examples/vue-complex/dist/js/chunk-vendors.a5f72d5d.js
  resources/todomvc/architecture-examples/vue-complex/dist/js/chunk-vendors.b4ac9361.js
  resources/todomvc/architecture-examples/vue-complex/dist/js/chunk-vendors.b4ac9361.js.map
  resources/todomvc/architecture-examples/vue/dist/index.html
  resources/todomvc/architecture-examples/vue/dist/js/app.414e2dd1.js
  resources/todomvc/architecture-examples/vue/dist/js/app.414e2dd1.js.map
  resources/todomvc/architecture-examples/vue/dist/js/app.ad36df07.js
  resources/todomvc/architecture-examples/vue/dist/js/app.ad36df07.js.map
  resources/todomvc/architecture-examples/vue/dist/js/chunk-vendors.a5f72d5d.js
  resources/todomvc/architecture-examples/vue/dist/js/chunk-vendors.b4ac9361.js
  resources/todomvc/architecture-examples/vue/dist/js/chunk-vendors.b4ac9361.js.map
  resources/todomvc/architecture-examples/vue/vue.config.js
Labels: trivial change, v3-blocker

#392 Update Testing.md to include Microsoft Edge
  Testing.md
Labels: trivial change

#391 Enable source maps in charts and editors
  resources/charts/dist/assets/chartjs-7fd89fd7.js
  resources/charts/dist/assets/chartjs-7fd89fd7.js.map
  resources/charts/dist/assets/developer-4ed993c7.js.map
  resources/charts/dist/assets/flights-airports-9a9e6422.js
  resources/charts/dist/assets/flights-airports-9a9e6422.js.map
  resources/charts/dist/assets/index-4ed993c7.js.map
  resources/charts/dist/assets/plot-37d2a5fb.js
  resources/charts/dist/assets/plot-37d2a5fb.js.map
  resources/charts/vite.config.js
  resources/editors/dist/assets/codemirror-521de7ab.js
  resources/editors/dist/assets/codemirror-521de7ab.js.map
  resources/editors/dist/assets/index.es-02a92ebc.js
  resources/editors/dist/assets/index.es-02a92ebc.js.map
  resources/editors/dist/assets/main-4ed993c7.js.map
  resources/editors/dist/assets/tiptap-95a40ba8.js
  resources/editors/dist/assets/tiptap-95a40ba8.js.map
  resources/editors/vite.config.js
Labels: v3-blocker

#397 Fix Cross-platform issue with npm script
  .github/workflows/test.yml
  package.json
  tests/run.mjs
Labels: trivial change

#398 chore: upgrade sinon to latest
  package-lock.json
  package.json
Labels: trivial change

#402 Remove duplicated word
  instructions.html
Labels: trivial change
