Repository WebKit/Speedometer, pull requests merged in 2025-02, with the labels that each got.

#485 Release/3.1: Update version text from 3.0 to 3.1
  InteractiveRunner.html
  about.html
  index.html
  instructions.html
Labels: trivial change, v3.1

#480 Release/3.1 - merge 408: Deconfuse Geomean Metric and geomean aggregate value
  index.html
  resources/benchmark-runner.mjs
  resources/metric.mjs
Labels: v3.1

#492 Use "next" as version ID on the main branch
  index.html
  resources/main.css
Labels: trivial change

#490 Score math: Add legend for variables
  resources/score.svg
Labels: trivial change

#494 Release/3.1 428 - add id to input (NEW - with correct base to merge into)
  resources/todomvc/architecture-examples/preact-complex/dist/app.js
  resources/todomvc/architecture-examples/preact-complex/dist/app.js.map
  resources/todomvc/architecture-examples/preact/dist/app.js
  resources/todomvc/architecture-examples/preact/dist/app.js.map
  resources/todomvc/architecture-examples/preact/src/app/main.js
  resources/todomvc/architecture-examples/react-complex/dist/app.bundle.js
  resources/todomvc/architecture-examples/react-complex/dist/app.bundle.js.map
  resources/todomvc/architecture-examples/react-redux-complex/dist/app.bundle.js
  resources/todomvc/architecture-examples/react-redux-complex/dist/app.bundle.js.map
  resources/todomvc/architecture-examples/react-redux/dist/app.bundle.js
  resources/todomvc/architecture-examples/react-redux/dist/app.bundle.js.map
  resources/todomvc/architecture-examples/react-redux/src/components/main.jsx
  resources/todomvc/architecture-examples/react/dist/app.bundle.js
  resources/todomvc/architecture-examples/react/dist/app.bundle.js.map
  resources/todomvc/architecture-examples/react/src/todo/components/main.jsx
Labels: v3.1
